//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.DataAccess.RMS.AffairService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.affair.services.v3x.seeyon.com")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceException1 serviceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceException", IsNullable=true, Order=0)]
        public ServiceException1 ServiceException1 {
            get {
                return this.serviceException1Field;
            }
            set {
                this.serviceException1Field = value;
                this.RaisePropertyChanged("ServiceException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceException", Namespace="http://services.v3x.seeyon.com/xsd")]
    public partial class ServiceException1 : Exception {
        
        private long errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("errorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.seeyon.com", ConfigurationName="AffairService.affairServicePortType")]
    public interface affairServicePortType {
        
        // CODEGEN: 消息 exportAgentPendingListRequest 的包装命名空间(http://impl.affair.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportAgentPendingList", ReplyAction="urn:exportAgentPendingListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.RMS.AffairService.ServiceException), Action="urn:exportAgentPendingListServiceException", Name="ServiceException", Namespace="http://impl.affair.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListResponse exportAgentPendingList(Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListRequest request);
        
        // CODEGEN: 消息 exportTrackListRequest 的包装命名空间(http://impl.affair.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportTrackList", ReplyAction="urn:exportTrackListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.RMS.AffairService.ServiceException), Action="urn:exportTrackListServiceException", Name="ServiceException", Namespace="http://impl.affair.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.RMS.AffairService.exportTrackListResponse exportTrackList(Sonluk.DataAccess.RMS.AffairService.exportTrackListRequest request);
        
        // CODEGEN: 消息 exportPendingListRequest 的包装命名空间(http://impl.affair.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportPendingList", ReplyAction="urn:exportPendingListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.RMS.AffairService.ServiceException), Action="urn:exportPendingListServiceException", Name="ServiceException", Namespace="http://impl.affair.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.RMS.AffairService.exportPendingListResponse exportPendingList(Sonluk.DataAccess.RMS.AffairService.exportPendingListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportAgentPendingList", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportAgentPendingListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticketId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=2)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=3)]
        public int pageSize;
        
        public exportAgentPendingListRequest() {
        }
        
        public exportAgentPendingListRequest(string tokenId, string ticketId, int firstNum, int pageSize) {
            this.tokenId = tokenId;
            this.ticketId = ticketId;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportAgentPendingListResponse", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportAgentPendingListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportAgentPendingListResponse() {
        }
        
        public exportAgentPendingListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportTrackList", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportTrackListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticketId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=2)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=3)]
        public int pageSize;
        
        public exportTrackListRequest() {
        }
        
        public exportTrackListRequest(string tokenId, string ticketId, int firstNum, int pageSize) {
            this.tokenId = tokenId;
            this.ticketId = ticketId;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportTrackListResponse", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportTrackListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportTrackListResponse() {
        }
        
        public exportTrackListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportPendingList", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportPendingListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticketId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=2)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=3)]
        public int pageSize;
        
        public exportPendingListRequest() {
        }
        
        public exportPendingListRequest(string tokenId, string ticketId, int firstNum, int pageSize) {
            this.tokenId = tokenId;
            this.ticketId = ticketId;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportPendingListResponse", WrapperNamespace="http://impl.affair.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportPendingListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.affair.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportPendingListResponse() {
        }
        
        public exportPendingListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface affairServicePortTypeChannel : Sonluk.DataAccess.RMS.AffairService.affairServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class affairServicePortTypeClient : System.ServiceModel.ClientBase<Sonluk.DataAccess.RMS.AffairService.affairServicePortType>, Sonluk.DataAccess.RMS.AffairService.affairServicePortType {
        
        public affairServicePortTypeClient() {
        }
        
        public affairServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public affairServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public affairServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public affairServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListResponse Sonluk.DataAccess.RMS.AffairService.affairServicePortType.exportAgentPendingList(Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListRequest request) {
            return base.Channel.exportAgentPendingList(request);
        }
        
        public string exportAgentPendingList(string tokenId, string ticketId, int firstNum, int pageSize) {
            Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListRequest inValue = new Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListRequest();
            inValue.tokenId = tokenId;
            inValue.ticketId = ticketId;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.RMS.AffairService.exportAgentPendingListResponse retVal = ((Sonluk.DataAccess.RMS.AffairService.affairServicePortType)(this)).exportAgentPendingList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.RMS.AffairService.exportTrackListResponse Sonluk.DataAccess.RMS.AffairService.affairServicePortType.exportTrackList(Sonluk.DataAccess.RMS.AffairService.exportTrackListRequest request) {
            return base.Channel.exportTrackList(request);
        }
        
        public string exportTrackList(string tokenId, string ticketId, int firstNum, int pageSize) {
            Sonluk.DataAccess.RMS.AffairService.exportTrackListRequest inValue = new Sonluk.DataAccess.RMS.AffairService.exportTrackListRequest();
            inValue.tokenId = tokenId;
            inValue.ticketId = ticketId;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.RMS.AffairService.exportTrackListResponse retVal = ((Sonluk.DataAccess.RMS.AffairService.affairServicePortType)(this)).exportTrackList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.RMS.AffairService.exportPendingListResponse Sonluk.DataAccess.RMS.AffairService.affairServicePortType.exportPendingList(Sonluk.DataAccess.RMS.AffairService.exportPendingListRequest request) {
            return base.Channel.exportPendingList(request);
        }
        
        public string exportPendingList(string tokenId, string ticketId, int firstNum, int pageSize) {
            Sonluk.DataAccess.RMS.AffairService.exportPendingListRequest inValue = new Sonluk.DataAccess.RMS.AffairService.exportPendingListRequest();
            inValue.tokenId = tokenId;
            inValue.ticketId = ticketId;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.RMS.AffairService.exportPendingListResponse retVal = ((Sonluk.DataAccess.RMS.AffairService.affairServicePortType)(this)).exportPendingList(inValue);
            return retVal.@return;
        }
    }
}
