//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.DataAccess.RMS.AuthorityService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.services.v3x.seeyon.com")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceException1 serviceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceException", IsNullable=true, Order=0)]
        public ServiceException1 ServiceException1 {
            get {
                return this.serviceException1Field;
            }
            set {
                this.serviceException1Field = value;
                this.RaisePropertyChanged("ServiceException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceException", Namespace="http://services.v3x.seeyon.com/xsd")]
    public partial class ServiceException1 : Exception {
        
        private long errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("errorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.services.v3x.seeyon.com")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.v3x.seeyon.com/xsd")]
    public partial class UserToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private UserToken nullTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public UserToken nullToken {
            get {
                return this.nullTokenField;
            }
            set {
                this.nullTokenField = value;
                this.RaisePropertyChanged("nullToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.seeyon.com", ConfigurationName="AuthorityService.authorityServicePortType")]
    public interface authorityServicePortType {
        
        // CODEGEN: 消息 authenticateRequest 的包装命名空间(http://impl.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:authenticate", ReplyAction="urn:authenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.RMS.AuthorityService.ServiceException), Action="urn:authenticateServiceException", Name="ServiceException", Namespace="http://impl.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.RMS.AuthorityService.authenticateResponse authenticate(Sonluk.DataAccess.RMS.AuthorityService.authenticateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticate", WrapperNamespace="http://impl.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class authenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public authenticateRequest() {
        }
        
        public authenticateRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateResponse", WrapperNamespace="http://impl.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sonluk.DataAccess.RMS.AuthorityService.UserToken @return;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(Sonluk.DataAccess.RMS.AuthorityService.UserToken @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface authorityServicePortTypeChannel : Sonluk.DataAccess.RMS.AuthorityService.authorityServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authorityServicePortTypeClient : System.ServiceModel.ClientBase<Sonluk.DataAccess.RMS.AuthorityService.authorityServicePortType>, Sonluk.DataAccess.RMS.AuthorityService.authorityServicePortType {
        
        public authorityServicePortTypeClient() {
        }
        
        public authorityServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public authorityServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authorityServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authorityServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.RMS.AuthorityService.authenticateResponse Sonluk.DataAccess.RMS.AuthorityService.authorityServicePortType.authenticate(Sonluk.DataAccess.RMS.AuthorityService.authenticateRequest request) {
            return base.Channel.authenticate(request);
        }
        
        public Sonluk.DataAccess.RMS.AuthorityService.UserToken authenticate(string userName, string password) {
            Sonluk.DataAccess.RMS.AuthorityService.authenticateRequest inValue = new Sonluk.DataAccess.RMS.AuthorityService.authenticateRequest();
            inValue.userName = userName;
            inValue.password = password;
            Sonluk.DataAccess.RMS.AuthorityService.authenticateResponse retVal = ((Sonluk.DataAccess.RMS.AuthorityService.authorityServicePortType)(this)).authenticate(inValue);
            return retVal.@return;
        }
    }
}
