using Sonluk.Entities.HR;
using Sonluk.Entities.MES;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sonluk.IDataAccess.HR
{
    public interface IADMINISTRATION_DORM
    {
        MES_RETURN INSERT(HR_ADMINISTRATION_DORM_DORM model);
        MES_RETURN UPDATE(HR_ADMINISTRATION_DORM_DORM model);
        HR_ADMINISTRATION_DORM_DORM_SELECT SELECT(HR_ADMINISTRATION_DORM_DORM model);
        MES_RETURN ROOM_INSERT(HR_ADMINISTRATION_DORM_ROOM model);
        HR_ADMINISTRATION_DORM_ROOM_SELECT ROOM_SELECT(HR_ADMINISTRATION_DORM_ROOM model);
        MES_RETURN ROOM_UPDATE(HR_ADMINISTRATION_DORM_ROOM model);
        MES_RETURN LIVE_INSERT(HR_ADMINISTRATION_DORM_LIVE model);
        HR_ADMINISTRATION_DORM_LIVE_SELECT LIVE_SELECT(HR_ADMINISTRATION_DORM_LIVE model);
        MES_RETURN LIVE_UPDATE(HR_ADMINISTRATION_DORM_LIVE model);
    }
}
