using Sonluk.Entities.HR;
using Sonluk.Entities.MES;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sonluk.IDataAccess.HR
{
    public interface IRY_RYINFO
    {
        HR_RY_RYINFO_SELECT INSERT(HR_RY_RYINFO model);
        HR_RY_RYINFO_SELECT SELECT(HR_RY_RYINFO model);
        HR_RY_RYINFO_SELECT SELECT_LB(HR_RY_RYINFO model, int LB);
        MES_RETURN UPDATE(HR_RY_RYINFO model);
        MES_RETURN UPDATE_ALL(HR_RY_RYINFO model);
        MES_RETURN UPDATE_PIC(HR_RY_RYINFO model);
        MES_RETURN UPDATE_CHECK(HR_RY_RYINFO model);
        MES_RETURN UPDATE_YGTYPE(List<HR_RY_RYINFO> model, int YGTYPE, int ZZZT);
        MES_RETURN UPDATE_DEPT(List<HR_RY_RYINFO> model, int DEPT, int GSBM);
        MES_RETURN UPDATE_JOBS(List<HR_RY_RYINFO> model, int JOBS);
        MES_RETURN UPDATE_QUIT(HR_RY_RYINFO model);
        MES_RETURN UPDATE_CHANGEINFO(HR_RY_RYINFO_CHANGEINFO model);
        MES_RETURN UPDATE_ISINGH(HR_RY_RYINFO model);
        MES_RETURN UPDATE_DUTYNAME(HR_RY_RYINFO model);
        HR_RY_RYINFO_SELECT SELECT_GSGL(HR_RY_RYINFO model);
        HR_RY_RYINFO_SELECT SELECT_WJGL(HR_RY_RYINFO model);
        HR_RY_RYINFO_SELECT SELECT_WBZW(HR_RY_RYINFO model);
        MES_RETURN INSERT_RONGY(HR_RY_RONGY model);
        HR_RY_RONGY_SELECT SELECT_RONGY(HR_RY_RONGY model);
        MES_RETURN UPDATE_RONGY(HR_RY_RONGY model);
        MES_RETURN DELETE_RONGY(int RONGYID);
        MES_RETURN INSERT_RONGY_RYID(int RONGYID, int RYID);
        MES_RETURN DELETE_RONGY_RYID(int RONGYID);
        HR_RY_RONGY_SELECT SELECT_RONGY_RYID(int RYID);
        MES_RETURN INSERT_RONGY_FILE(HR_RY_RONGY model);
        HR_RY_RONGY_SELECT SELECT_RONGY_FILE(int RONGYID);
        MES_RETURN DELETE_RONGY_FILE(int RYFILEID);
        HR_RY_LZINFO_SELECT SELECT_LZINFO(HR_RY_RYINFO model);
        HR_RY_CHANGEINFO_SELECT SELECT_RY_CHANGEINFO(HR_RY_RYINFO_CHANGEINFO model);
        MES_RETURN UPDATE_LB(HR_RY_RYINFO model);
    }
}
