//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.DataAccess.OA.Seeyon.MessageAPI {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.message.services.v3x.seeyon.com")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceException1 serviceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceException", IsNullable=true, Order=0)]
        public ServiceException1 ServiceException1 {
            get {
                return this.serviceException1Field;
            }
            set {
                this.serviceException1Field = value;
                this.RaisePropertyChanged("ServiceException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceException", Namespace="http://services.v3x.seeyon.com/xsd")]
    public partial class ServiceException1 : Exception {
        
        private long errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("errorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.message.services.v3x.seeyon.com")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ctp.seeyon.com/xsd")]
    public partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private long errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private long resultField;
        
        private bool resultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("errorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
                this.RaisePropertyChanged("resultSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.seeyon.com", ConfigurationName="Seeyon.MessageAPI.messageServicePortType")]
    public interface messageServicePortType {
        
        // CODEGEN: 消息 sendMessageByLoginNameRequest 的包装命名空间(http://impl.message.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendMessageByLoginName", ReplyAction="urn:sendMessageByLoginNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceException), Action="urn:sendMessageByLoginNameServiceException", Name="ServiceException", Namespace="http://impl.message.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameResponse sendMessageByLoginName(Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameRequest request);
        
        // CODEGEN: 消息 sendMessageByUserIdRequest 的包装命名空间(http://impl.message.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendMessageByUserId", ReplyAction="urn:sendMessageByUserIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceException), Action="urn:sendMessageByUserIdServiceException", Name="ServiceException", Namespace="http://impl.message.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdResponse sendMessageByUserId(Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageByLoginName", WrapperNamespace="http://impl.message.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class sendMessageByLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("loginNames", IsNullable=true)]
        public string[] loginNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("url", IsNullable=true)]
        public string[] url;
        
        public sendMessageByLoginNameRequest() {
        }
        
        public sendMessageByLoginNameRequest(string token, string[] loginNames, string content, string[] url) {
            this.token = token;
            this.loginNames = loginNames;
            this.content = content;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageByLoginNameResponse", WrapperNamespace="http://impl.message.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class sendMessageByLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse @return;
        
        public sendMessageByLoginNameResponse() {
        }
        
        public sendMessageByLoginNameResponse(Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageByUserId", WrapperNamespace="http://impl.message.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class sendMessageByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("userIds")]
        public long[] userIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("url", IsNullable=true)]
        public string[] url;
        
        public sendMessageByUserIdRequest() {
        }
        
        public sendMessageByUserIdRequest(string token, long[] userIds, string content, string[] url) {
            this.token = token;
            this.userIds = userIds;
            this.content = content;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageByUserIdResponse", WrapperNamespace="http://impl.message.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class sendMessageByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.message.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse @return;
        
        public sendMessageByUserIdResponse() {
        }
        
        public sendMessageByUserIdResponse(Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface messageServicePortTypeChannel : Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class messageServicePortTypeClient : System.ServiceModel.ClientBase<Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType>, Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType {
        
        public messageServicePortTypeClient() {
        }
        
        public messageServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public messageServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameResponse Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType.sendMessageByLoginName(Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameRequest request) {
            return base.Channel.sendMessageByLoginName(request);
        }
        
        public Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse sendMessageByLoginName(string token, string[] loginNames, string content, string[] url) {
            Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameRequest inValue = new Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameRequest();
            inValue.token = token;
            inValue.loginNames = loginNames;
            inValue.content = content;
            inValue.url = url;
            Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByLoginNameResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType)(this)).sendMessageByLoginName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdResponse Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType.sendMessageByUserId(Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdRequest request) {
            return base.Channel.sendMessageByUserId(request);
        }
        
        public Sonluk.DataAccess.OA.Seeyon.MessageAPI.ServiceResponse sendMessageByUserId(string token, long[] userIds, string content, string[] url) {
            Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdRequest inValue = new Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdRequest();
            inValue.token = token;
            inValue.userIds = userIds;
            inValue.content = content;
            inValue.url = url;
            Sonluk.DataAccess.OA.Seeyon.MessageAPI.sendMessageByUserIdResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.MessageAPI.messageServicePortType)(this)).sendMessageByUserId(inValue);
            return retVal.@return;
        }
    }
}
