//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.DataAccess.OA.Seeyon.DocumentAPI {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.document.services.v3x.seeyon.com")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceException1 serviceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceException", IsNullable=true, Order=0)]
        public ServiceException1 ServiceException1 {
            get {
                return this.serviceException1Field;
            }
            set {
                this.serviceException1Field = value;
                this.RaisePropertyChanged("ServiceException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceException", Namespace="http://services.v3x.seeyon.com/xsd")]
    public partial class ServiceException1 : Exception {
        
        private long errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("errorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.document.services.v3x.seeyon.com")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.edoc.v3x.seeyon.com/xsd")]
    public partial class EdocSignReceipt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string opinionField;
        
        private string receipientField;
        
        private long signTimeField;
        
        private bool signTimeFieldSpecified;
        
        private string signUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string opinion {
            get {
                return this.opinionField;
            }
            set {
                this.opinionField = value;
                this.RaisePropertyChanged("opinion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string receipient {
            get {
                return this.receipientField;
            }
            set {
                this.receipientField = value;
                this.RaisePropertyChanged("receipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long signTime {
            get {
                return this.signTimeField;
            }
            set {
                this.signTimeField = value;
                this.RaisePropertyChanged("signTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signTimeSpecified {
            get {
                return this.signTimeFieldSpecified;
            }
            set {
                this.signTimeFieldSpecified = value;
                this.RaisePropertyChanged("signTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string signUnit {
            get {
                return this.signUnitField;
            }
            set {
                this.signUnitField = value;
                this.RaisePropertyChanged("signUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.java/xsd")]
    public partial class Map : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool emptyField;
        
        private bool emptyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
                this.RaisePropertyChanged("empty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emptySpecified {
            get {
                return this.emptyFieldSpecified;
            }
            set {
                this.emptyFieldSpecified = value;
                this.RaisePropertyChanged("emptySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.seeyon.com", ConfigurationName="Seeyon.DocumentAPI.documentServicePortType")]
    public interface documentServicePortType {
        
        // CODEGEN: 消息 signEdocToRestRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:signEdocToRest", ReplyAction="urn:signEdocToRestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:signEdocToRestServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestResponse signEdocToRest(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestRequest request);
        
        // CODEGEN: 消息 exportGroupNewsRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportGroupNews", ReplyAction="urn:exportGroupNewsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportGroupNewsServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsResponse exportGroupNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsRequest request);
        
        // CODEGEN: 消息 exportRecentNewsRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportRecentNews", ReplyAction="urn:exportRecentNewsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportRecentNewsServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsResponse exportRecentNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsRequest request);
        
        // CODEGEN: 消息 exportFlow2Request 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportFlow2", ReplyAction="urn:exportFlow2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportFlow2ServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Response exportFlow2(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Request request);
        
        // CODEGEN: 消息 exportBbsRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportBbs", ReplyAction="urn:exportBbsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportBbsServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsResponse exportBbs(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsRequest request);
        
        // CODEGEN: 消息 exportOfflineFormModelRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportOfflineFormModel", ReplyAction="urn:exportOfflineFormModelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportOfflineFormModelServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelResponse exportOfflineFormModel(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelRequest request);
        
        // CODEGEN: 消息 exportNewsRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportNews", ReplyAction="urn:exportNewsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportNewsServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsResponse exportNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsRequest request);
        
        // CODEGEN: 消息 exportBulletinByDateTimeRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportBulletinByDateTime", ReplyAction="urn:exportBulletinByDateTimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportBulletinByDateTimeServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeResponse exportBulletinByDateTime(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeRequest request);
        
        // CODEGEN: 消息 exportGroupBulletinRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportGroupBulletin", ReplyAction="urn:exportGroupBulletinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportGroupBulletinServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinResponse exportGroupBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinRequest request);
        
        // CODEGEN: 消息 exportEdocRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportEdoc", ReplyAction="urn:exportEdocResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportEdocServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocResponse exportEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocRequest request);
        
        // CODEGEN: 消息 updateEdocStateRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:updateEdocState", ReplyAction="urn:updateEdocStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:updateEdocStateServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateResponse updateEdocState(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateRequest request);
        
        // CODEGEN: 消息 exportResearchRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportResearch", ReplyAction="urn:exportResearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportResearchServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchResponse exportResearch(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchRequest request);
        
        // CODEGEN: 消息 importEdocRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:importEdoc", ReplyAction="urn:importEdocResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:importEdocServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocResponse importEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocRequest request);
        
        // CODEGEN: 消息 exportBulletinRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportBulletin", ReplyAction="urn:exportBulletinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportBulletinServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinResponse exportBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinRequest request);
        
        // CODEGEN: 消息 processEdocReceiveRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:processEdocReceive", ReplyAction="urn:processEdocReceiveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:processEdocReceiveServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveResponse processEdocReceive(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveRequest request);
        
        // CODEGEN: 消息 signEdoc 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:signEdoc")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:signEdocServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        void signEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdoc request);
        
        // CODEGEN: 消息 exportRecentAccountBulletinByAccountIdRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportRecentAccountBulletinByAccountId", ReplyAction="urn:exportRecentAccountBulletinByAccountIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportRecentAccountBulletinByAccountIdServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdResponse exportRecentAccountBulletinByAccountId(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdRequest request);
        
        // CODEGEN: 消息 exportRecentAccountBulletinRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportRecentAccountBulletin", ReplyAction="urn:exportRecentAccountBulletinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportRecentAccountBulletinServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinResponse exportRecentAccountBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinRequest request);
        
        // CODEGEN: 消息 processEdocSendRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:processEdocSend", ReplyAction="urn:processEdocSendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:processEdocSendServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendResponse processEdocSend(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendRequest request);
        
        // CODEGEN: 消息 exportFlowRequest 的包装命名空间(http://impl.document.services.v3x.seeyon.com)以后生成的消息协定与默认值(www.seeyon.com)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportFlow", ReplyAction="urn:exportFlowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.ServiceException), Action="urn:exportFlowServiceException", Name="ServiceException", Namespace="http://impl.document.services.v3x.seeyon.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdocSignReceipt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowResponse exportFlow(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signEdocToRest", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class signEdocToRestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public long edocSendId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sonluk.DataAccess.OA.Seeyon.DocumentAPI.Map param;
        
        public signEdocToRestRequest() {
        }
        
        public signEdocToRestRequest(long edocSendId, Sonluk.DataAccess.OA.Seeyon.DocumentAPI.Map param) {
            this.edocSendId = edocSendId;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signEdocToRestResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class signEdocToRestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public int @return;
        
        public signEdocToRestResponse() {
        }
        
        public signEdocToRestResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportGroupNews", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportGroupNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        public int pageSize;
        
        public exportGroupNewsRequest() {
        }
        
        public exportGroupNewsRequest(string token, string ticket, int firstNum, int pageSize) {
            this.token = token;
            this.ticket = ticket;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportGroupNewsResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportGroupNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportGroupNewsResponse() {
        }
        
        public exportGroupNewsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentNews", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=4)]
        public int pageSize;
        
        public exportRecentNewsRequest() {
        }
        
        public exportRecentNewsRequest(string token, long accountId, string ticket, int firstNum, int pageSize) {
            this.token = token;
            this.accountId = accountId;
            this.ticket = ticket;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentNewsResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportRecentNewsResponse() {
        }
        
        public exportRecentNewsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportFlow2", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportFlow2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long flowId;
        
        public exportFlow2Request() {
        }
        
        public exportFlow2Request(string token, long flowId) {
            this.token = token;
            this.flowId = flowId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportFlow2Response", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportFlow2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportFlow2Response() {
        }
        
        public exportFlow2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBbs", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBbsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long bbsId;
        
        public exportBbsRequest() {
        }
        
        public exportBbsRequest(string token, long bbsId) {
            this.token = token;
            this.bbsId = bbsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBbsResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBbsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportBbsResponse() {
        }
        
        public exportBbsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOfflineFormModel", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportOfflineFormModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long s_affairId;
        
        public exportOfflineFormModelRequest() {
        }
        
        public exportOfflineFormModelRequest(string token, long s_affairId) {
            this.token = token;
            this.s_affairId = s_affairId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOfflineFormModelResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportOfflineFormModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public exportOfflineFormModelResponse() {
        }
        
        public exportOfflineFormModelResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportNews", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        public long newsId;
        
        public exportNewsRequest() {
        }
        
        public exportNewsRequest(string token, string ticket, long newsId) {
            this.token = token;
            this.ticket = ticket;
            this.newsId = newsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportNewsResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportNewsResponse() {
        }
        
        public exportNewsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBulletinByDateTime", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBulletinByDateTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beginDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endDateTime;
        
        public exportBulletinByDateTimeRequest() {
        }
        
        public exportBulletinByDateTimeRequest(string token, string ticket, string accountName, string beginDateTime, string endDateTime) {
            this.token = token;
            this.ticket = ticket;
            this.accountName = accountName;
            this.beginDateTime = beginDateTime;
            this.endDateTime = endDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBulletinByDateTimeResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBulletinByDateTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportBulletinByDateTimeResponse() {
        }
        
        public exportBulletinByDateTimeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportGroupBulletin", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportGroupBulletinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        public int pageSize;
        
        public exportGroupBulletinRequest() {
        }
        
        public exportGroupBulletinRequest(string token, string ticket, int firstNum, int pageSize) {
            this.token = token;
            this.ticket = ticket;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportGroupBulletinResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportGroupBulletinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportGroupBulletinResponse() {
        }
        
        public exportGroupBulletinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportEdoc", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportEdocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long documentId;
        
        public exportEdocRequest() {
        }
        
        public exportEdocRequest(string token, long documentId) {
            this.token = token;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportEdocResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportEdocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportEdocResponse() {
        }
        
        public exportEdocResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEdocState", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class updateEdocStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long edocSendId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=4)]
        public int state;
        
        public updateEdocStateRequest() {
        }
        
        public updateEdocStateRequest(string tokenId, long edocSendId, string accountId, string accountName, int state) {
            this.tokenId = tokenId;
            this.edocSendId = edocSendId;
            this.accountId = accountId;
            this.accountName = accountName;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEdocStateResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class updateEdocStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public int @return;
        
        public updateEdocStateResponse() {
        }
        
        public updateEdocStateResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportResearch", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportResearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long researchId;
        
        public exportResearchRequest() {
        }
        
        public exportResearchRequest(string token, long researchId) {
            this.token = token;
            this.researchId = researchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportResearchResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportResearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportResearchResponse() {
        }
        
        public exportResearchResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importEdoc", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class importEdocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml;
        
        public importEdocRequest() {
        }
        
        public importEdocRequest(string token, string xml) {
            this.token = token;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importEdocResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class importEdocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public long @return;
        
        public importEdocResponse() {
        }
        
        public importEdocResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBulletin", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBulletinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticketId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        public long bulltinId;
        
        public exportBulletinRequest() {
        }
        
        public exportBulletinRequest(string token, string ticketId, long bulltinId) {
            this.token = token;
            this.ticketId = ticketId;
            this.bulltinId = bulltinId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportBulletinResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportBulletinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportBulletinResponse() {
        }
        
        public exportBulletinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processEdocReceive", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class processEdocReceiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long receiveId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recNo;
        
        public processEdocReceiveRequest() {
        }
        
        public processEdocReceiveRequest(string token, long receiveId, string loginName, string recNo) {
            this.token = token;
            this.receiveId = receiveId;
            this.loginName = loginName;
            this.recNo = recNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processEdocReceiveResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class processEdocReceiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public int @return;
        
        public processEdocReceiveResponse() {
        }
        
        public processEdocReceiveResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signEdoc", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class signEdoc {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long edocSendId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sonluk.DataAccess.OA.Seeyon.DocumentAPI.EdocSignReceipt receipt;
        
        public signEdoc() {
        }
        
        public signEdoc(string token, long edocSendId, Sonluk.DataAccess.OA.Seeyon.DocumentAPI.EdocSignReceipt receipt) {
            this.token = token;
            this.edocSendId = edocSendId;
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentAccountBulletinByAccountId", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentAccountBulletinByAccountIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=4)]
        public int pageSize;
        
        public exportRecentAccountBulletinByAccountIdRequest() {
        }
        
        public exportRecentAccountBulletinByAccountIdRequest(string token, long accountId, string ticket, int firstNum, int pageSize) {
            this.token = token;
            this.accountId = accountId;
            this.ticket = ticket;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentAccountBulletinByAccountIdResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentAccountBulletinByAccountIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportRecentAccountBulletinByAccountIdResponse() {
        }
        
        public exportRecentAccountBulletinByAccountIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentAccountBulletin", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentAccountBulletinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=3)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=4)]
        public int pageSize;
        
        public exportRecentAccountBulletinRequest() {
        }
        
        public exportRecentAccountBulletinRequest(string token, string accountName, string ticket, int firstNum, int pageSize) {
            this.token = token;
            this.accountName = accountName;
            this.ticket = ticket;
            this.firstNum = firstNum;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportRecentAccountBulletinResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportRecentAccountBulletinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportRecentAccountBulletinResponse() {
        }
        
        public exportRecentAccountBulletinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processEdocSend", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class processEdocSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long edocSendId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginName;
        
        public processEdocSendRequest() {
        }
        
        public processEdocSendRequest(string token, long edocSendId, string loginName) {
            this.token = token;
            this.edocSendId = edocSendId;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processEdocSendResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class processEdocSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        public int @return;
        
        public processEdocSendResponse() {
        }
        
        public processEdocSendResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportFlow", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=1)]
        public long flowId;
        
        public exportFlowRequest() {
        }
        
        public exportFlowRequest(string token, long flowId) {
            this.token = token;
            this.flowId = flowId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportFlowResponse", WrapperNamespace="http://impl.document.services.v3x.seeyon.com", IsWrapped=true)]
    public partial class exportFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.document.services.v3x.seeyon.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public exportFlowResponse() {
        }
        
        public exportFlowResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface documentServicePortTypeChannel : Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class documentServicePortTypeClient : System.ServiceModel.ClientBase<Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType>, Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType {
        
        public documentServicePortTypeClient() {
        }
        
        public documentServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public documentServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public documentServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public documentServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.signEdocToRest(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestRequest request) {
            return base.Channel.signEdocToRest(request);
        }
        
        public int signEdocToRest(long edocSendId, Sonluk.DataAccess.OA.Seeyon.DocumentAPI.Map param) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestRequest();
            inValue.edocSendId = edocSendId;
            inValue.param = param;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdocToRestResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).signEdocToRest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportGroupNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsRequest request) {
            return base.Channel.exportGroupNews(request);
        }
        
        public string exportGroupNews(string token, string ticket, int firstNum, int pageSize) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsRequest();
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupNewsResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportGroupNews(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportRecentNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsRequest request) {
            return base.Channel.exportRecentNews(request);
        }
        
        public string exportRecentNews(string token, long accountId, string ticket, int firstNum, int pageSize) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsRequest();
            inValue.token = token;
            inValue.accountId = accountId;
            inValue.ticket = ticket;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentNewsResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportRecentNews(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Response Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportFlow2(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Request request) {
            return base.Channel.exportFlow2(request);
        }
        
        public string exportFlow2(string token, long flowId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Request inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Request();
            inValue.token = token;
            inValue.flowId = flowId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlow2Response retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportFlow2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportBbs(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsRequest request) {
            return base.Channel.exportBbs(request);
        }
        
        public string exportBbs(string token, long bbsId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsRequest();
            inValue.token = token;
            inValue.bbsId = bbsId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBbsResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportBbs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportOfflineFormModel(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelRequest request) {
            return base.Channel.exportOfflineFormModel(request);
        }
        
        public string[] exportOfflineFormModel(string token, long s_affairId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelRequest();
            inValue.token = token;
            inValue.s_affairId = s_affairId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportOfflineFormModelResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportOfflineFormModel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportNews(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsRequest request) {
            return base.Channel.exportNews(request);
        }
        
        public string exportNews(string token, string ticket, long newsId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsRequest();
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.newsId = newsId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportNewsResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportNews(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportBulletinByDateTime(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeRequest request) {
            return base.Channel.exportBulletinByDateTime(request);
        }
        
        public string exportBulletinByDateTime(string token, string ticket, string accountName, string beginDateTime, string endDateTime) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeRequest();
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.accountName = accountName;
            inValue.beginDateTime = beginDateTime;
            inValue.endDateTime = endDateTime;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinByDateTimeResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportBulletinByDateTime(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportGroupBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinRequest request) {
            return base.Channel.exportGroupBulletin(request);
        }
        
        public string exportGroupBulletin(string token, string ticket, int firstNum, int pageSize) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinRequest();
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportGroupBulletinResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportGroupBulletin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocRequest request) {
            return base.Channel.exportEdoc(request);
        }
        
        public string exportEdoc(string token, long documentId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocRequest();
            inValue.token = token;
            inValue.documentId = documentId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportEdocResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportEdoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.updateEdocState(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateRequest request) {
            return base.Channel.updateEdocState(request);
        }
        
        public int updateEdocState(string tokenId, long edocSendId, string accountId, string accountName, int state) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateRequest();
            inValue.tokenId = tokenId;
            inValue.edocSendId = edocSendId;
            inValue.accountId = accountId;
            inValue.accountName = accountName;
            inValue.state = state;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.updateEdocStateResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).updateEdocState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportResearch(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchRequest request) {
            return base.Channel.exportResearch(request);
        }
        
        public string exportResearch(string token, long researchId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchRequest();
            inValue.token = token;
            inValue.researchId = researchId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportResearchResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportResearch(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.importEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocRequest request) {
            return base.Channel.importEdoc(request);
        }
        
        public long importEdoc(string token, string xml) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocRequest();
            inValue.token = token;
            inValue.xml = xml;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.importEdocResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).importEdoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinRequest request) {
            return base.Channel.exportBulletin(request);
        }
        
        public string exportBulletin(string token, string ticketId, long bulltinId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinRequest();
            inValue.token = token;
            inValue.ticketId = ticketId;
            inValue.bulltinId = bulltinId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportBulletinResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportBulletin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.processEdocReceive(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveRequest request) {
            return base.Channel.processEdocReceive(request);
        }
        
        public int processEdocReceive(string token, long receiveId, string loginName, string recNo) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveRequest();
            inValue.token = token;
            inValue.receiveId = receiveId;
            inValue.loginName = loginName;
            inValue.recNo = recNo;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocReceiveResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).processEdocReceive(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.signEdoc(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdoc request) {
            base.Channel.signEdoc(request);
        }
        
        public void signEdoc(string token, long edocSendId, Sonluk.DataAccess.OA.Seeyon.DocumentAPI.EdocSignReceipt receipt) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdoc inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.signEdoc();
            inValue.token = token;
            inValue.edocSendId = edocSendId;
            inValue.receipt = receipt;
            ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).signEdoc(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportRecentAccountBulletinByAccountId(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdRequest request) {
            return base.Channel.exportRecentAccountBulletinByAccountId(request);
        }
        
        public string exportRecentAccountBulletinByAccountId(string token, long accountId, string ticket, int firstNum, int pageSize) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdRequest();
            inValue.token = token;
            inValue.accountId = accountId;
            inValue.ticket = ticket;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinByAccountIdResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportRecentAccountBulletinByAccountId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportRecentAccountBulletin(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinRequest request) {
            return base.Channel.exportRecentAccountBulletin(request);
        }
        
        public string exportRecentAccountBulletin(string token, string accountName, string ticket, int firstNum, int pageSize) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinRequest();
            inValue.token = token;
            inValue.accountName = accountName;
            inValue.ticket = ticket;
            inValue.firstNum = firstNum;
            inValue.pageSize = pageSize;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportRecentAccountBulletinResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportRecentAccountBulletin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.processEdocSend(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendRequest request) {
            return base.Channel.processEdocSend(request);
        }
        
        public int processEdocSend(string token, long edocSendId, string loginName) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendRequest();
            inValue.token = token;
            inValue.edocSendId = edocSendId;
            inValue.loginName = loginName;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.processEdocSendResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).processEdocSend(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowResponse Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType.exportFlow(Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowRequest request) {
            return base.Channel.exportFlow(request);
        }
        
        public string exportFlow(string token, long flowId) {
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowRequest inValue = new Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowRequest();
            inValue.token = token;
            inValue.flowId = flowId;
            Sonluk.DataAccess.OA.Seeyon.DocumentAPI.exportFlowResponse retVal = ((Sonluk.DataAccess.OA.Seeyon.DocumentAPI.documentServicePortType)(this)).exportFlow(inValue);
            return retVal.@return;
        }
    }
}
